spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=bezkoder_db

# Server Port
server.port=8278

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000

# Enable Redis
spring.cache.type=redis
spring.cache.redis.time-to-live=60000

# Log level
logging.level.org.springframework.data.mongodb.core=DEBUG
logging.level.org.springframework.data.redis=DEBUG
logging.level.org.springframework.cache=DEBUG